{% set version = "1.4.0" %}

package:
  name: genson
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/genson/genson-{{ version }}.tar.gz
  sha256: bc7f1c1bae87a21ca44d81149aec95a3f4468d676de9b8b08caa064f3c50b3da
  patches:
    - 75.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
  entry_points:
    - genson = genson.__main__:main
  skip: true  # [py<39]

requirements:
  build:
  host:
    - python
    - wheel
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - genson
  source_files:
    - test
  requires:
    - pip
    - jsonschema >=4.0.0
    - pytest
    - python
  commands:
    - pip check
    - pytest test -v -k "not test_no_input"
    - genson --help

about:
  home: https://github.com/wolverdude/genson/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: GenSON is a powerful, user-friendly JSON Schema generator.
  dev_url: https://github.com/wolverdude/genson/
  doc_url: https://github.com/wolverdude/GenSON/blob/master/README.rst
  description: GenSON is a powerful, user-friendly JSON Schema generator built in Python.

extra:
  recipe-maintainers:
    - pmlandwehr
