{% set version = "1.1.0" %}

package:
  name: genson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/genson/genson-{{ version }}.tar.gz
  sha256: 7557f5c989ddc194a4dbdfc828520d911922f932dc076c7e850774162f61d6d5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - genson = genson.cli:main

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - genson

  commands:
    - genson --help

about:
  home: https://github.com/wolverdude/genson/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'GenSON is a powerful, user-friendly JSON Schema generator.'
  dev_url: https://github.com/wolverdude/genson/

extra:
  recipe-maintainers:
    - pmlandwehr
