travis:
  secure:
    BINSTAR_TOKEN: MMvNLZh5XxFBKFXAxzLzfKORKH2x/XMP8zXxU8iOVXs1vR8OjdIZZniCeS9fVY3RclnE/bwr95UpS0WRZplN/dHniiV3XPcWyldvxHbrr4aAbE9kKh8ejJepX1ambdiwiBF7DXEPWAdzY4ev3F8t/f3gtQzMMuJxe9K6jYv/J+UX7IHeUDCzi8pSCm/opp55pQT08gXf18dO27ZeMbp7lk2WlhjYilQstqI3E9RFII5O7kJj8XB8zOAYHQKCrDXt62Uw/7HQNl2EjASJS22YasIv7+Wj/cXEPqyeG6i/NkscN+Xdl27O0BKgZev+T6hF5lvS5Qavibe8xiNQeghFaeD4MqvCK1R5lzvmJeRv3r0h0JkHOgpH+9iegJK5TgeFdFLAyLZfIl0ul+MNzLmX03nse5rRxbczwFxHKSA5aV1tjqEZLMgSjwWwhwlxKiQix+pKFHbHANt98V0RY7o/ft8WD57T1OZl1Mbw+ZkaSvuzxuvrxDQgZhLTLZ1Y2dtCnlcW7DYfeOTWwHDjZUeYFB0/Q8B42wvxtWWimhDxMYGLr+xOmEiSTUNNyJIn19Vpd/DfQWdRWKzbWXLm8THJjAyiggMkLDVrZDvcxSsA84GoEOYBO3braaZGvRDazhxutwajZcSto/+AN0qXS/DLo1nO9MH8gm/fdDd+ncw4roA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
