travis:
  secure:
    BINSTAR_TOKEN: iCyVYBH2FnCZ3y2wbpcd51OGwi7oKXhvdPVPaJJGbz4dcU5UzB9iVZFqMUDTAUVEFQ3xCrkoylp/ns+vuG59Nb/WTf4BJ/PU0QZ/JvpZPMz1DwyckXuRPwVe4+z20y1N5+n9E3PA0A1+ecvIkZ4t1uNbSe5FdfV8ovqf7xCP3fHBTnLlz0n1P1kXcLgZ/dwyS22Iowm/dMTphTicmiP1lxUY9VihjabGyKb66sbAbBkFzaJjjdI7p3utiYWrUbEC0DbVWHXRe71uSMiWQktQDKwDiWx//6R1lQJGl1478aoZT+yC47ynvcsNPPUXHAC2RMYwYjsQQA6Oc1eIsa64HiiBcjwGNqj91nNRqH+FfUph1ZafO9roCHDcsH60q9twTV/DS6pMZCMVPmhtPbRxKyZB/WikqvlMH4Wmx5TDATCj+CCpAUBuFIt8G0wbkUEKNKdzIlZThmVqGfUUrvbzYEWcgvWNzk92p8uvW8b2KuLBaGvng31CnXmksIy723IIzhtMwCcMlwa3PmZmUMF50LBsDQtiZ/zyrOA5NEFWm02oOWPZrNyUW2UNBJuHoi39A5WzQ6GXEke0b3LDwEgO9J56ADfOVw4iFWy4sazte/YAjgvQzF+2wChgKWWK2Ap/AztmH4idPAFIR7sCreXflMj+7Mv4dqgaQhqblSJ5zZk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
